Repository IntelPython/scikit-learn_bench, pull requests merged in 2021-01, with the labels that each got.

#48 Update README.md - Add articles for xgboost
  README.md
Labels: docs

#47 Update copyright for 2021 year
  bench.py
  cuml_bench/dbscan.py
  cuml_bench/df_clsf.py
  cuml_bench/df_regr.py
  cuml_bench/elasticnet.py
  cuml_bench/kmeans.py
  cuml_bench/knn_clsf.py
  cuml_bench/lasso.py
  cuml_bench/linear.py
  cuml_bench/log_reg.py
  cuml_bench/pca.py
  cuml_bench/ridge.py
  cuml_bench/svm.py
  cuml_bench/train_test_split.py
  daal4py_bench/dbscan.py
  daal4py_bench/df_clsf.py
  daal4py_bench/df_regr.py
  daal4py_bench/distances.py
  daal4py_bench/kmeans.py
  daal4py_bench/linear.py
  daal4py_bench/pca.py
  daal4py_bench/ridge.py
  datasets/load_datasets.py
  datasets/loader.py
  datasets/make_datasets.py
  modelbuilders_bench/lgbm_mb.py
  modelbuilders_bench/utils.py
  modelbuilders_bench/xgb_mb.py
  report_generator/report_generator.py
  runner.py
  sklearn_bench/dbscan.py
  sklearn_bench/df_clsf.py
  sklearn_bench/df_regr.py
  sklearn_bench/distances.py
  sklearn_bench/elasticnet.py
  sklearn_bench/kmeans.py
  sklearn_bench/knn_clsf.py
  sklearn_bench/lasso.py
  sklearn_bench/linear.py
  sklearn_bench/log_reg.py
  sklearn_bench/pca.py
  sklearn_bench/ridge.py
  sklearn_bench/svm.py
  sklearn_bench/train_test_split.py
  utils.py
  xgboost_bench/gbt.py
Labels: infra

#49 Small extensions & add new dataset
  configs/cuml_config.json
  datasets/load_datasets.py
  datasets/loader.py
  runner.py
Labels: datasets, extend

#50 PCA Config Update and Imports Fix
  configs/skl_config.json
  sklearn_bench/dbscan.py
  sklearn_bench/df_clsf.py
  sklearn_bench/df_regr.py
  sklearn_bench/distances.py
  sklearn_bench/elasticnet.py
  sklearn_bench/kmeans.py
  sklearn_bench/knn_clsf.py
  sklearn_bench/lasso.py
  sklearn_bench/linear.py
  sklearn_bench/log_reg.py
  sklearn_bench/pca.py
  sklearn_bench/ridge.py
  sklearn_bench/svm.py
  sklearn_bench/train_test_split.py
Labels: bug, extend

#51 Fix parameters for RF in config and fix n_jobs for original scikit-learn
  bench.py
  configs/skl_config.json
  sklearn_bench/dbscan.py
  sklearn_bench/df_clsf.py
  sklearn_bench/df_regr.py
  sklearn_bench/knn_clsf.py
Labels: bug
