Repository IntelPython/scikit-learn_bench, pull requests merged in 2021-04, with the labels that each got.

#58 Applied mypy + flake8 + ISort for all files
  azure-pipelines.yml
  bench.py
  cuml_bench/__init__.py
  cuml_bench/dbscan.py
  cuml_bench/df_clsf.py
  cuml_bench/df_regr.py
  cuml_bench/elasticnet.py
  cuml_bench/kmeans.py
  cuml_bench/knn_clsf.py
  cuml_bench/lasso.py
  cuml_bench/linear.py
  cuml_bench/log_reg.py
  cuml_bench/pca.py
  cuml_bench/ridge.py
  cuml_bench/svm.py
  cuml_bench/train_test_split.py
  daal4py_bench/__init__.py
  daal4py_bench/dbscan.py
  daal4py_bench/df_clsf.py
  daal4py_bench/df_regr.py
  daal4py_bench/distances.py
  daal4py_bench/kmeans.py
  daal4py_bench/linear.py
  daal4py_bench/pca.py
  daal4py_bench/ridge.py
  datasets/load_datasets.py
  datasets/loader.py
  datasets/make_datasets.py
  modelbuilders_bench/__init__.py
  modelbuilders_bench/lgbm_mb.py
  modelbuilders_bench/mb_utils.py
  modelbuilders_bench/xgb_mb.py
  report_generator/report_generator.py
  runner.py
  sklearn_bench/dbscan.py
  sklearn_bench/df_clsf.py
  sklearn_bench/df_regr.py
  sklearn_bench/distances.py
  sklearn_bench/elasticnet.py
  sklearn_bench/kmeans.py
  sklearn_bench/knn_clsf.py
  sklearn_bench/lasso.py
  sklearn_bench/linear.py
  sklearn_bench/log_reg.py
  sklearn_bench/pca.py
  sklearn_bench/ridge.py
  sklearn_bench/svm.py
  sklearn_bench/train_test_split.py
  utils.py
  xgboost_bench/__init__.py
  xgboost_bench/gbt.py
Labels: enhancement, infra

#61 Update readme for sklearnex
  README.md
  azure-pipelines.yml
  bench.py
Labels: docs

#59 Add GPU benchmarks support to readme
  README.md
  configs/README.md
  configs/skl_xpu_config.json
Labels: docs

#62 Add support proba svc; add pypi info; fix errors
  README.md
  bench.py
  configs/svm/svc_proba_cuml.json
  configs/svm/svc_proba_sklearn.json
  cuml_bench/README.md
  cuml_bench/svm.py
  datasets/loader.py
  runner.py
  sklearn_bench/README.md
  sklearn_bench/requirements.txt
  sklearn_bench/svm.py
  utils.py
  xgboost_bench/README.md
  xgboost_bench/requirements.txt
Labels: bug, extend

#63 Update CI - replace conda on pip download
  azure-pipelines.yml
Labels: infra

#64 Update conda channel in README
  README.md
  sklearn_bench/README.md
Labels: docs

#65 Add catboost article
  README.md
Labels: datasets

#66 Add device information in the report json file
  bench.py
  utils.py
Labels: enhancement, gpu

#60 Xgb datasets adding
  README.md
  azure-pipelines.yml
  bench.py
  configs/README.md
  configs/cuml_config.json
  configs/lgbm_mb_cpu_config.json
  configs/modelbuilders/lgbm_mb_cpu_config.json
  configs/modelbuilders/xgb_mb_cpu_config.json
  configs/skl_config.json
  configs/svm/svc_proba_cuml.json
  configs/svm/svc_proba_sklearn.json
  configs/testing/daal4py_xgboost.json
  configs/testing/xgboost.json
  configs/xgb_cpu_config.json
  configs/xgb_gpu_config.json
  configs/xgb_mb_cpu_config.json
  configs/xgboost/xgb_cpu_additional_config.json
  configs/xgboost/xgb_cpu_main_config.json
  configs/xgboost/xgb_gpu_config.json
  cuml_bench/README.md
  daal4py_bench/README.md
  datasets/load_datasets.py
  datasets/loader.py
  datasets/loader_classification.py
  datasets/loader_multiclass.py
  datasets/loader_regression.py
  datasets/loader_utils.py
  runner.py
  sklearn_bench/README.md
  sklearn_bench/requirements.txt
  utils.py
  xgboost_bench/README.md
  xgboost_bench/gbt.py
  xgboost_bench/requirements.txt
Labels: datasets, enhancement, extend
